#!/usr/bin/env bash
# [CORE ENGINE: Production-grade Bash Builder with Output Directory Support]

set -euo pipefail

# Color formatting variables
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

print_info() { echo -e "${BLUE}[INFO]${NC} $1"; }
print_success() { echo -e "${GREEN}[SUCCESS]${NC} $1"; }
print_warn() { echo -e "${YELLOW}[WARN]${NC} $1"; }
print_error() { echo -e "${RED}[ERROR]${NC} $1" >&2; exit 1; }

# Get absolute paths
CORE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(dirname "$CORE_DIR")"
SNIPPETS_DIR="$ROOT_DIR/snippets"
RECIPES_DIR="$ROOT_DIR/recipes"
OUTPUT_DIR="$ROOT_DIR/output"

# Check if recipe name is provided
if [ $# -lt 1 ]; then
    print_error "Usage: ./core/builder.sh <recipe_name>\nExample: ./core/builder.sh web-app-py"
fi

RECIPE_NAME="$1"
RECIPE_DIR="$RECIPES_DIR/$RECIPE_NAME"
RECIPE_CFG="$RECIPE_DIR/recipe.cfg"

if [ ! -f "$RECIPE_CFG" ]; then
    print_error "Recipe configuration not found at: $RECIPE_CFG"
fi

print_info "Loading recipe: $RECIPE_NAME"
source "$RECIPE_CFG"

# Validate required variables
if [ -z "${IMAGE_NAME:-}" ] || [ -z "${PIPELINE:-}" ]; then
    print_error "Recipe configuration is missing mandatory variables (IMAGE_NAME or PIPELINE)."
fi

IMAGE_TAG="${IMAGE_TAG:-latest}"

# Define recipe specific output directory
RECIPE_OUTPUT_DIR="$OUTPUT_DIR/$RECIPE_NAME"
mkdir -p "$RECIPE_OUTPUT_DIR"
DOCKERFILE_PATH="$RECIPE_OUTPUT_DIR/Dockerfile"

# Detect host architecture
HOST_ARCH=$(uname -m)
case "$HOST_ARCH" in
    x86_64) DOCKER_ARCH="amd64" ;;
    aarch64|arm64) DOCKER_ARCH="arm64" ;;
    *) DOCKER_ARCH="amd64" ;;
esac
print_info "Detected Host Architecture: $HOST_ARCH (Mapping to: $DOCKER_ARCH)"

# --- STEP 1: Pre-flight validation of all snippets ---
print_info "Validating pipeline snippets..."
for snippet in "${PIPELINE[@]}"; do
    snippet_file="$SNIPPETS_DIR/${snippet}.dockerfile"
    if [ ! -f "$snippet_file" ]; then
        print_error "Missing snippet file: $snippet_file (referenced in pipeline)"
    fi
done
print_success "All pipeline snippets verified."

# --- STEP 2: Assembling the Dockerfile into output/ ---
print_info "Assembling final Dockerfile..."
{
    echo "# ========================================================"
    echo "# AUTO-GENERATED BY container-craft builder"
    echo "# Recipe: $IMAGE_NAME"
    echo "# Target Architecture: $DOCKER_ARCH"
    echo "# ========================================================"
    echo ""

    for snippet in "${PIPELINE[@]}"; do
        snippet_file="$SNIPPETS_DIR/${snippet}.dockerfile"
        echo "# --- START SNIPPET: $snippet ---"
        cat "$snippet_file"
        echo -e "\n# --- END SNIPPET: $snippet ---\n"
    done
} > "$DOCKERFILE_PATH"

print_success "Dockerfile generated at: $DOCKERFILE_PATH"

# --- STEP 3: Trigger Docker Build using Recipe DIR as context ---
FULL_IMAGE_TAG="${IMAGE_NAME}:${IMAGE_TAG}"
print_info "Triggering Docker build for: $FULL_IMAGE_TAG"

# Run docker build using the generated Dockerfile but pointing to recipe directory for context (requirements.txt, app.py)
if docker build --build-arg TARGET_ARCH="$DOCKER_ARCH" -t "$FULL_IMAGE_TAG" -f "$DOCKERFILE_PATH" "$RECIPE_DIR"; then
    print_success "Successfully built and tagged image: $FULL_IMAGE_TAG"
    print_info "Inspection Dockerfile preserved at: $DOCKERFILE_PATH"
else
    print_error "Docker build failed."
fi